[package]
name = "payments-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.3", features = ["derive"] }
csv = "1.3.1"
fixed = { version = "1.28.0", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
